version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-db:/data/db
    networks:
      - jwt_network
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 900 1 --loglevel warning
    volumes:
      - ./cache:/data
    networks:
      - jwt_network
  api:
    container_name: api
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: "3000"
    depends_on:
      - mongo
    networks:
      - jwt_network

networks:
  jwt_network:
    driver: bridge